package spacelift

import (
	"context"
	"fmt"
	"os"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	fwprovider "github.com/hashicorp/terraform-plugin-framework/provider"
	fwschema "github.com/hashicorp/terraform-plugin-framework/provider/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/spacelift-io/terraform-provider-spacelift/spacelift/internal"
)

type frameworkProvider struct {
	commit  string
	version string
}

// NewFrameworkProvider returns a Plugin Framework provider. Starts with no resources
// or data sources; each migrated resource is added to Resources()/DataSources().
func NewFrameworkProvider(commit, version string) fwprovider.Provider {
	return &frameworkProvider{commit: commit, version: version}
}

func (p *frameworkProvider) Metadata(_ context.Context, _ fwprovider.MetadataRequest, resp *fwprovider.MetadataResponse) {
	resp.TypeName = "spacelift"
	resp.Version = p.version
}

func (p *frameworkProvider) Schema(_ context.Context, _ fwprovider.SchemaRequest, resp *fwprovider.SchemaResponse) {
	resp.Schema = fwschema.Schema{
		Attributes: map[string]fwschema.Attribute{
			"api_key_endpoint": fwschema.StringAttribute{
				Description: "Endpoint to use when authenticating with an API key outside of Spacelift",
				Optional:    true,
			},
			"api_key_id": fwschema.StringAttribute{
				Description: "ID of the API key to use when executing outside of Spacelift",
				Optional:    true,
			},
			"api_key_secret": fwschema.StringAttribute{
				Description: "API key secret to use when executing outside of Spacelift",
				Optional:    true,
				Sensitive:   true,
			},
			"api_token": fwschema.StringAttribute{
				Description: "Spacelift token generated by a run, only useful from within Spacelift",
				Optional:    true,
				Sensitive:   true,
			},
		},
	}
}

type frameworkProviderModel struct {
	APIKeyEndpoint types.String `tfsdk:"api_key_endpoint"`
	APIKeyID       types.String `tfsdk:"api_key_id"`
	APIKeySecret   types.String `tfsdk:"api_key_secret"`
	APIToken       types.String `tfsdk:"api_token"`
}

func (p *frameworkProvider) Configure(ctx context.Context, req fwprovider.ConfigureRequest, resp *fwprovider.ConfigureResponse) {
	var config frameworkProviderModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Fall back to environment variables when config values are not set.
	endpoint := firstNonEmpty(config.APIKeyEndpoint.ValueString(), os.Getenv("SPACELIFT_API_KEY_ENDPOINT"))
	keyID := firstNonEmpty(config.APIKeyID.ValueString(), os.Getenv("SPACELIFT_API_KEY_ID"))
	keySecret := firstNonEmpty(config.APIKeySecret.ValueString(), os.Getenv("SPACELIFT_API_KEY_SECRET"))
	token := firstNonEmpty(config.APIToken.ValueString(), os.Getenv("SPACELIFT_API_TOKEN"))

	hasAllAPIKeyFields := endpoint != "" && keyID != "" && keySecret != ""
	hasToken := token != ""

	var client *internal.Client
	var err error

	switch {
	case hasAllAPIKeyFields:
		client, err = buildClientFromAPIKeyParams(endpoint, keyID, keySecret)
		if err != nil {
			resp.Diagnostics.AddError("could not build API client", err.Error())
			return
		}
	case hasToken:
		client, err = buildClientFromToken(token)
		if err != nil {
			resp.Diagnostics.AddError("could not build API client", err.Error())
			return
		}
	default:
		missing := []string{}
		if endpoint == "" {
			missing = append(missing, "api_key_endpoint")
		}
		if keyID == "" {
			missing = append(missing, "api_key_id")
		}
		if keySecret == "" {
			missing = append(missing, "api_key_secret")
		}
		resp.Diagnostics.AddError(
			"provider not configured",
			fmt.Sprintf(
				"either the API key must be set or the following settings must be provided: %s",
				strings.Join(missing, ", "),
			),
		)
		return
	}

	client.Commit = p.commit
	client.Version = p.version

	resp.DataSourceData = client
	resp.ResourceData = client
}

func (p *frameworkProvider) Resources(_ context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		NewNamedWebhookResource,
	}
}

func (p *frameworkProvider) DataSources(_ context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{}
}

// firstNonEmpty returns the first non-empty string from the provided values.
func firstNonEmpty(values ...string) string {
	for _, v := range values {
		if v != "" {
			return v
		}
	}
	return ""
}
