name: Build package

on: { push: { branches-ignore: [future, main] } }

jobs:
  registry:
    name: Build package
    runs-on: ubuntu-latest
    container: golang:1.17

    steps:
      - name: Check out repository code
        uses: actions/checkout@master

      - name: Install utilities
        run: |
          apt-get update -y
          apt-get install -y awscli gettext-base zip

      - name: Import the PGP key
        env:
          GPG_KEY_BASE64: ${{ secrets.GPG_KEY_BASE64 }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo ${GPG_KEY_BASE64} | base64 -d > spacelift.gpg
          gpg --import \
            --passphrase=$GPG_PASSPHRASE \
            --pinentry-mode=loopback \
            spacelift.gpg
          rm spacelift.gpg

      - name: Download dependencies to keep the build clean
        run: go mod download

      - name: Build the package
        env:
          DOMAIN: spacelift.dev
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: ./registry/package.sh
