name: Production registry

on: [push]

jobs:
  registry:
    name: Publish the provider to the registry
    runs-on: ubuntu-latest
    container: golang:1.16

    steps:
      - name: Check out repository code
        uses: actions/checkout@master

      - name: Install utilities
        run: |
          apt-get update -y
          apt-get install -y awscli gettext-base zip

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Import the PGP key
        env:
          GPG_KEY_BASE64: ${{ secrets.GPG_KEY_BASE64 }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo ${GPG_KEY_BASE64} | base64 -d > spacelift.gpg
          gpg --import \
            --passphrase=$GPG_PASSPHRASE \
            --pinentry-mode=loopback \
            spacelift.gpg
          rm spacelift.gpg

      - name: Download dependencies to keep the build clean
        run: go mod download

      - name: Build the package
        env:
          DOMAIN: spacelift.dev
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: ./registry/package.sh

      - name: Test uploading the provider data to S3
        run: >-
          aws s3 sync
          build s3://${{ secrets.AWS_S3_BUCKET }}/v1/providers/spacelift-io/spacelift
          --no-progress
          --delete
          --dryrun

      - name: Upload the provider data to S3
        if: github.ref == 'refs/heads/master'
        run: >-
          aws s3 sync
          build s3://${{ secrets.AWS_S3_BUCKET }}/v1/providers/spacelift-io/spacelift
          --no-progress
          --delete

      - name: Invalidate cache
        if: github.ref == 'refs/heads/master'
        run: >-
          aws cloudfront create-invalidation
          --distribution-id ${{ secrets.DISTRIBUTION }}
          --paths "/v1/providers/spacelift-io/spacelift/*"
